### ISSUE TITLE
sqlite3.OperationalError: no such table: PYPROPHET_WEIGHTS

### ISSUE THREAD

**Issue by yachliu** [PyProphet/pyprophet#105]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas-1.2.2-py3.9-linux-x86_64.egg/pandas/io/sql.py", line 1697, in execute
    cur.execute(*args, **kwargs)
sqlite3.OperationalError: no such table: PYPROPHET_WEIGHTS

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyprophet-2.1.10-py3.9-linux-x86_64.egg/pyprophet/runner.py", line 455, in __init__
    data = pd.read_sql_query("SELECT * FROM PYPROPHET_WEIGHTS WHERE LEVEL=='%s'" % self.level, con)
  File "/usr/local/lib/python3.9/site-packages/pandas-1.2.2-py3.9-linux-x86_64.egg/pandas/io/sql.py", line 377, in read_sql_query
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.9/site-packages/pandas-1.2.2-py3.9-linux-x86_64.egg/pandas/io/sql.py", line 1743, in read_query
    cursor = self.execute(*args)
  File "/usr/local/lib/python3.9/site-packages/pandas-1.2.2-py3.9-linux-x86_64.egg/pandas/io/sql.py", line 1709, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT * FROM PYPROPHET_WEIGHTS WHERE LEVEL=='ms1ms2'': no such table: PYPROPHET_WEIGHTS
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas-1.2.2-py3.9-linux-x86_64.egg/pandas/io/sql.py", line 1697, in execute
    cur.execute(*args, **kwargs)
sqlite3.OperationalError: no such table: PYPROPHET_WEIGHTS

```shell
for run in BGS_*.osw
do
run_subsampled=${run}s # generates .osws files
pyprophet subsample --in=$run --out=$run_subsampled --subsample_ratio=0.1
done

pyprophet merge --template=MCB_spikearabi_10percent_MSF_DDA_lib.withDecoys.pqp --out=model.osw *.osws

pyprophet score \
--in=model.osw \
--classifier=XGBoost \
--level=ms1ms2 \
--ss_iteration_fdr=0.01 \
--parametric \
--threads=48

for run in BGS_*.osw
do
pyprophet score --in=$run --apply_weights=model.osw --level=ms1ms2
done
```

**Comment by singjc** [comment]
Hi, 

The issue occurs because when you score on **model.osw** you specify the XGBoost classifier. When you apply the weights, you don't specify to use the XGBoost classifier (the default is LDA, which uses `PYPROHPET_WEGIHTS`.

You should run the following:

```
for run in BGS_*.osw
do
pyprophet score --in=$run --classifier=XGBoost --apply_weights=model.osw --level=ms1ms2
done
```

Hope this helps!

Best,

Justin

**Comment by yachliu** [comment]
Thank you very much!
