### ISSUE TITLE
Swath2stat analysis

### ISSUE THREAD

**Issue by mchiapello** [PyProphet/pyprophet#31]
Is ti pyprophet able to export datasets compatible with R package Swath2Stat?

I exported a tsv using the following command:

`pyprophet export --in=data/merged.osw --out=data/legacy.tsv`

The file does not look like the one I can see in the R package. Am I missing somenthing?

**Comment by grosenberger** [comment]
Usually SWATH2stats expects the output to be processed by TRIC. You can also apply TRIC to a single file, it will just filter the results to the selected cutoffs and append the additional columns.

**Comment by mchiapello** [comment]
I run the following pipeline: 

```
pyprophet score --in data/osw_output.osw --protein

pyprophet protein --in data/osw_output.osw --context run-specific

pyprophet export --in data/osw_output.osw --out data/protein_inference_FDR001.tsv --protein

feature_alignment.py --in data/protein_inference_FDR001.tsv --out data/TRIC_protein_inference_FDR001.tsv --method LocalMST --realign_method lowess_cython --max_rt_diff 60 --mst:useRTCorrection True --mst:Stdev_multiplier 3.0 --target_fdr 0.01 --max_fdr_quality 0.05
```

I Got the following error running TRIC:

> Parsing input files
> Traceback (most recent call last):
>  File "/usr/local/bin/feature_alignment.py", line 4, in <module>
    __import__('pkg_resources').run_script('msproteomicstools==0.8.0', 'feature_alignment.py')
>  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
>  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
>  File "/usr/local/lib/python2.7/dist-packages/msproteomicstools-0.8.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/feature_alignment.py", line 799, in <module>
>  File "/usr/local/lib/python2.7/dist-packages/msproteomicstools-0.8.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/feature_alignment.py", line 741, in main
>  File "build/bdist.linux-x86_64/egg/msproteomicstoolslib/format/SWATHScoringReader.py", line 169, in parse_files
> KeyError: 'run_id'

Any clue about what I am doing wrong?

**Comment by summerghw** [comment]
@mchiapello  Hi，I have got the same error, did you figure out what is wrong ?  could you tell me how to fix this
