### ISSUE TITLE
error of using pyprophet-cli 

### ISSUE THREAD

**Issue by Hitlikegh** [PyProphet/pyprophet#97]
Hi,
I have installed pyprophet (version 2.1.10) and pyprophet-cli (version 0.0.19). However, an error occurred when I used pyprophet-cli.

The BUG is shown as follows:
============================================================================
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\pyprophet-cli-script.py", line 11, in <module>
    load_entry_point('pyprophet-cli==0.0.19', 'console_scripts', 'pyprophet-cli')()
  File "C:\Miniconda3\lib\site-packages\pkg_resources\__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Miniconda3\lib\site-packages\pkg_resources\__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "C:\Miniconda3\lib\site-packages\pkg_resources\__init__.py", line 2325, in load
    return self.resolve()
  File "C:\Miniconda3\lib\site-packages\pkg_resources\__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Miniconda3\lib\site-packages\pyprophet_cli-0.0.19-py3.7.egg\pyprophet_cli\main.py", line 17, in <module>
    from . import score
  File "C:\Miniconda3\lib\site-packages\pyprophet_cli-0.0.19-py3.7.egg\pyprophet_cli\score.py", line 16, in <module>
    from pyprophet.stats import (calculate_final_statistics, summary_err_table,
ImportError: cannot import name 'calculate_final_statistics' from 'pyprophet.stats' (C:\Miniconda3\lib\site-packages\pyprophet-2.1.10-py3.7-win-amd64.egg\pyprophet\stats.py)
=================================================================================

How can I fix this BUG?

I found that pyprophet-cli hasn't been updated for a long time.  How to use the current pyprophet?

Thanks!

**Comment by grosenberger** [comment]
We don't recommend the use ``pyprophet-cli`` anymore, all functionality has been reimplemented in``pyprophet`` > 2.0. However, this requires to export the OpenSWATH results in the SQLite-based OSW format. You can find more information here: http://openswath.org/en/latest/docs/pyprophet.html

**Comment by Hitlikegh** [comment]
Thank you so much for your help.
